### ISSUE TITLE
Relaxing dependencies

### ISSUE THREAD

**Issue by JakkuSakura** [Ellipsis-Labs/phoenix-seat-manager-v1#7]
I observed the following dependencies. `=` dependencies makes it very hard to integrate into other libraries
```toml
[dependencies]
phoenix-v1 = { version = "0.2.2", features = [ "no-entrypoint" ] }
shank = "=0.0.12"
solana-program = "=1.14.9"
bytemuck = "=1.13.0"
borsh = "=0.9.3"
lib-sokoban = "=0.3.0" 
num_enum = "=0.5.9"
itertools = "=0.10.5"
thiserror = "=1.0.38"
ellipsis-macros = "=0.1.1" 
solana-security-txt = "=1.1.0"
static_assertions = "=1.1.0"
spl-token = { version = "=3.5.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "=1.1.1", features = [ "no-entrypoint" ] } 
toml_edit = "=0.18.1"
proc-macro-crate = "=1.3.0"
```
